name: Build List

on: 
  workflow_dispatch:
  
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: List Releases
        # run: gh release list --exclude-drafts
        uses: github-actions-tools/gh-list-releases@v0.0.3
        id: list-releases
        
      - run: |
          echo '${{ steps.list-releases.outputs.releases }}'
      
